# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('weixin', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True, verbose_name='备注')),
                ('create_date', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
