# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='部门')),
                ('remarks', models.CharField(blank=True, max_length=64, verbose_name='备注')),
                ('owner', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '组',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.MyGroup', verbose_name='部门或组'),
        ),
    ]
