# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20180731_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygroup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='group',
        ),
        migrations.DeleteModel(
            name='MyGroup',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
