# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20180817_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionoperation',
            options={'verbose_name': '通知类型', 'verbose_name_plural': '通知类型'},
        ),
        migrations.AlterModelOptions(
            name='eventlog',
            options={'verbose_name': '事件纪录', 'verbose_name_plural': '事件纪录'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': '维护', 'verbose_name_plural': '维护'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': '模板', 'verbose_name_plural': '模板'},
        ),
        migrations.AlterModelOptions(
            name='trigger',
            options={'verbose_name': '触发器', 'verbose_name_plural': '触发器'},
        ),
        migrations.AlterModelOptions(
            name='triggerexpression',
            options={'verbose_name': '表达式', 'verbose_name_plural': '表达式'},
        ),
    ]
