# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20180817_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'verbose_name': '主机组', 'verbose_name_plural': '主机组'},
        ),
    ]
